### ISSUE TITLE
[Feature Request] Retain fluid when broken

### ISSUE THREAD

**Issue by MysticAura** [EwyBoy/ITank#10]
This mod is well done so far. The main thing I noticed was that it loses it's fluid when dismantled/broken. This would add a ton more uses for your tanks if implemented.

**Comment by EwyBoy** [comment]
I am working on it but when the tanks are broken they don't render properly when they have a liquid inside. Still working on fixing this before I implement that feature 👍

**Comment by edenprojectde** [comment]
This should have been written in the info.. its 5 onths after and the tanks still dont hold liquids. It doesnt matter if they render correctly just draw them without liquid inside the inventory.. Tanks are pretty much useless w/o this.

**Comment by EwyBoy** [comment]
And another 5 months went by and as of build 1.1.2-1.1X.2 it has finally been added in. Enjoy!
https://minecraft.curseforge.com/projects/itank/files
