### ISSUE TITLE
Itank Lag

### ISSUE THREAD

**Issue by Cazadorsniper** [EwyBoy/ITank#11]
I noticed that I get a bit of lag when looking at Itanks when fluids are inside of them. My fps is usually at 300ish but the tanks causefps to drop to 180ish.

**Comment by EwyBoy** [comment]
Hmm thanks for the feedback, I look into it and will see if I can optimize the rendering / logic

**Comment by EwyBoy** [comment]
Took me a while to figure out this one. But with my new fluid renderer we are now running at stable 60FPS with a chunk filled with tanks stacked all the way up into the sky.
https://minecraft.curseforge.com/projects/itank/files/2563387
