### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by rigis1** [EwyBoy/ITank#13]
modification does not work on the version 1.12.1

**Comment by EwyBoy** [comment]
I don't have a clue what you are talking about? You have to be more specific with version and tell me a bit more about what is not working.

**Comment by iamcarrotmaster** [comment]
do you think you culd make the next update be 1.12.1 compatable is what i think they mean, if not that would be great.

**Comment by EwyBoy** [comment]
Who plays 1.12.1? Why does it not work on 1.12.1, give me a crash report.

**Comment by iamcarrotmaster** [comment]
there wasnt a crash it just said itanks cant run on 1.12.1 it runs on 1.12.2
