### ISSUE TITLE
Multiblock tank causing performance problems

### ISSUE THREAD

**Issue by Lanternglow** [EwyBoy/ITank#14]
I had a 3-block tank full of liquid starlight from Astral Sorcery. It was causing my frame rate to drop to about 10-15 fps. Leaving the area and unloading that chunk returned my frame rate to normal (60 fps is my max frame rate setting). Setting them down as three separate 1-block tanks also returns my frame rate to normal (this is my current work-around). 

My uneducated guess is that the tank autodrain to lower tank feature is triggering block updates on the other tanks in an unconstrained loop. But I am not a mod author, so there is a lot about the block ticking and block updating framework that I don't understand.

**Comment by EwyBoy** [comment]
Took me a while to figure out this one. But with my new fluid renderer we are now running at stable 60FPS with a chunk filled with tanks stacked all the way up into the sky.
https://minecraft.curseforge.com/projects/itank/files/2563387
