### ISSUE TITLE
Suggestion: Display tank contents in inventory

### ISSUE THREAD

**Issue by Ithronyar** [EwyBoy/ITank#16]
When tanks are broken and placed in the inventory, they don't show their contents. They should at least show a tooltip; something like "Stored: Lava (1000mB)".

Ideally, they should have a tooltip _and_ render the fluid inside the tank, so you don't need to mouse over them to see what's inside.

**Comment by EwyBoy** [comment]
Working on a way to render fluids while tank is broken now.

**Comment by Tokeli** [comment]
Fluid rendering isn't needed, but a tooltip showing the fluid contents would be extremely helpful, as they're completely identical to empty tanks until you place them down.

**Comment by EwyBoy** [comment]
Added tool-tips with fluid and capacity info and some other fixes in the latest build I just compiled:

Download & Changelog: https://minecraft.curseforge.com/projects/itank/files/2627330

Code changes: https://github.com/EwyBoy/ITank/commit/13084dd8eb7c064f923d115c40beb10593bbec9f

**Comment by EwyBoy** [comment]
Also spent a few hours looking into way to render fluids in the tank when in item form, but having tons of issues and can't get it to work.
