### ISSUE TITLE
Fluids from Create do not render in tanks

### ISSUE THREAD

**Issue by niraqw** [EwyBoy/ITank#19]
The fluids "Chocolate" and "Honey" added by the mod Create are invisible when in ITank tanks. This is purely a visual bug, as the liquids can be put into and taken out of the tanks without issue. Additionally, potion fluids, also added by Create, are visible in ITank tanks but all display as white, when they should be the color of the potion.

**Comment by EwyBoy** [comment]
ITank uses the standard fluid rendering provided by Forge and works for all fluids coded this way.

Create is a weird mod and codes their things in a weird modular way. I normally would not go out of my way to code a fix for this but I enjoy playing with create so I will attempt to create a fix. If it ends up being to hard, Create has to fix their shit.

Will look into this next week and keep you updated on the issue. Thanks for the report.

-Ewy

**Comment by EwyBoy** [comment]
![2021-05-18_18 26 38](https://user-images.githubusercontent.com/5883716/118689346-30539d00-b807-11eb-8d4c-52421f610efe.png)
![2021-05-18_18 26 30](https://user-images.githubusercontent.com/5883716/118689350-30ec3380-b807-11eb-8457-3a45ad30d9a8.png)
Managed to fix it.

**Comment by EwyBoy** [comment]
https://www.curseforge.com/minecraft/mc-mods/itank/files/3313915
