### ISSUE TITLE
Unable to pick up placed tanks

### ISSUE THREAD

**Issue by Irritated-Badger** [EwyBoy/ITank#20]
**Describe the bug**
Unable to pick up placed tanks. I've tried using everything from pickaxes to fist, the break animation appear and the sound plays like it was broken, but the tank remains where it was.

**To Reproduce**
1. Place tank
2. Hit to repeatedly to break it and pick it up
3. ???
4. Tank stays where it was placed

**Expected behavior**
The ability to pick up a placed tank.

Forge Version: 36.1.23
Mod Version: ITank-1.16.5 1.4.0

**Comment by EwyBoy** [comment]
Something has gone terribly wrong here, I am working on a fix

**Comment by EwyBoy** [comment]
The bug is patched. Thanks for reporting.
https://www.curseforge.com/minecraft/mc-mods/itank/files/3319612
