### ISSUE TITLE
[Bug] Tank doesn't retain liquid

### ISSUE THREAD

**Issue by Jegethy** [EwyBoy/ITank#23]
###### **Minecraft Version**
> 1.16.5

###### **Forge Version**
> 36.1.16

###### **Mod Version**
> ITank-1.16.5-1.4.2
> Bibliotheca-1.16.5-1.6.2 (if this matters)

###### **Describe the bug**
> iTank blocks don't retain liquid. I've tested this with water and lava, using Ender Tanks and Refined Pipes.

###### **How to reproduce**
> Place a tank, fill it with liquid, break it.

**Comment by EwyBoy** [comment]
This is not a bug, this is feature has not yet been implemented for ITank 1.16.+. 
There is a huge ITank update coming out tomorrow with colored tanks, new fluid retaining and much more. Prob release in 12 hours ish. Just have to finish up the testing and update the Language file.

**Comment by Jegethy** [comment]
> This is not a bug, this is feature has not yet been implemented for ITank 1.16.+.
> There is a huge ITank update coming out tomorrow with colored tanks, new fluid retaining and much more. Prob release in 12 hours ish. Just have to finish up the testing and update the Language file.

Awesome, I'm looking forward to it!

**Comment by EwyBoy** [comment]
https://www.curseforge.com/minecraft/mc-mods/itank/files/3347622
