### ISSUE TITLE
Duping Bug

### ISSUE THREAD

**Issue by Vitamin-Carrot** [EwyBoy/ITank#4]
Placing a single empty tank and then mining it with a pickaxe results in two tanks being dropped

**Comment by Vitamin-Carrot** [comment]
The dropped tanks appear to have different id's as some will stack and others will start a new stack in the players inventory

**Comment by EwyBoy** [comment]
I am sure I fixed this yesterday

**Comment by EwyBoy** [comment]
I am having a look at it now

**Comment by EwyBoy** [comment]
Fixed now, it was some old code who I deleted yesterday but got back into the workspace after having some trouble with git. Build on CF in a bit.

**Comment by EwyBoy** [comment]
https://minecraft.curseforge.com/projects/itank

**Comment by Vitamin-Carrot** [comment]
Confirmed resolved

On 12/01/2017 1:18 PM, EwyBoy wrote:

Closed #4<https://github.com/EwyBoy/ITank/issues/4>.
