### ISSUE TITLE
Tanks with different types of fluids still connect

### ISSUE THREAD

**Issue by starg09** [EwyBoy/ITank#5]
Saw [this comment](https://www.reddit.com/r/feedthebeast/comments/5ndwl1/just_released_a_new_mod_itank/dcb7be9/) on the reddit announcement, and while I like the connected rendering in itself, the connecting on different fluids does seem like a bug. Would you consider eventually adding some special case so they render separately in that scenario? Nothing of high priority, but when you have some time =)

![5ga3hbp](https://cloud.githubusercontent.com/assets/1235066/21873832/fab3a65e-d84f-11e6-95a5-2fa9cfd4f2f3.png)

**Comment by EwyBoy** [comment]
Nope, it is suppose to be like that cause when you have high tower of tanks the fluids of the same liquid will stack together and will be drained in order. This can be useful when you are dealing with molten metals from tinkers construct and such. This is not a bug, I am not gonna change it either.

**Comment by starg09** [comment]
Oh, I see! Having now tested it myself, it actually seems like a pretty cool way of sorting the liquids! It may lead to some interesting builds using that liquid sorting as a mechanic :D

**Comment by EwyBoy** [comment]
^^
