### ISSUE TITLE
[Cross-mod] "Ender Fluid Conduits" from Ender IO misbehaving with ITanks

### ISSUE THREAD

**Issue by starg09** [EwyBoy/ITank#8]
Versions used:

* Forge 2209
* Ender IO 3.1.157
* EnderCore 0.4.1.62
* ITank 1.0.2

These are the particular situations that I've noticed, but there may be more:

1. When using an Ender Fluid Conduit on Extract mode, with "Redstone Mode" set to "Active With Signal", it will extract a couple of buckets out of the ITank (8 at most, at least from my testing), then stop sending, no matter how many times the redstone signal is applied again. Replacing the conduit seems to make it work again. Also, **the liquid isn't removed from the ITank, so this could be used as a dupe bug.**

2. When using an Ender Fluid Conduit on Extract mode, but with "Redstone Mode" set to "Always Active", the liquid will be extracted properly, without duping nor stopping midway.

3. ITanks won't fill when connected to an Ender Fluid Conduit set on "Insert Only". It is detected by the conduit, but it just won't insert the liquid.

4. When using either regular Fluid Conduits, or Pressurized Fluid Conduits, none of the above happens (they behave correctly).

Reporting as I haven't noticed this happening with any tank from other mods. Could you please let me know if I should cross-post this to Ender IO's tracker?

* [A video showing points 1 and 2](https://my.mixtape.moe/coefkb.mp4) (Tested with Liquid XP, but in my experience it happens with any liquid)

* [A video showing point 3](https://my.mixtape.moe/qsplgb.mp4)

**Comment by EwyBoy** [comment]
Thanks, I will look into it later today ^^

**Comment by EwyBoy** [comment]
I am struggeling to find out whats causing this bug..
