### ISSUE TITLE
Crash on client load.

### ISSUE THREAD

**Issue by CelticChristoph** [EwyBoy/ITank#9]
MC Version: 1.10.2
Forge version: 12.18.3.2209

Honestly not sure why it's crashing, but it crashes on load-up. It appears to be a "duplicate entity", but I don't know with which mod its ID clashing?

Crash-log here:
[Log](https://gist.github.com/CelticChristoph/a8795eadb935058e2db1192da5b8231dl)

**Comment by EwyBoy** [comment]
The crash log link is broken, take me to a 404. Also whats the build version of the mod?

**Comment by EwyBoy** [comment]
It might be a render ID conflicting with another mods render ID. Going to look into it. But if u can send me a new link to the log it would be helpfull ^^

**Comment by EwyBoy** [comment]
I think I managed to fix the problem with the conflicting IDs. 
Should be fixed in the new build coming out today.
But it will remove all tanks from existing worlds.

**Comment by CelticChristoph** [comment]
Alrighty, sounds good!

And the removal of tanks isn't an issue for me, as I could never launch the game with them to begin with. xP

**Comment by EwyBoy** [comment]
^^
